package br.com.amooora.users.service;

import br.com.amooora.users.dto.PhotoMetadata;
import br.com.amooora.users.service.storage.StorageService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.time.ZonedDateTime;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserPhotoServiceTest {

    @Mock
    private StorageService storageService;

    @Mock
    private MultipartFile mockFile;

    @InjectMocks
    private UserPhotoService userPhotoService;

    private static final String USER_ID = "123";
    private static final String PHOTO_NAME = "test-photo.jpg";
    private static final byte[] PHOTO_DATA = "test-data".getBytes();
    private static final String CONTENT_TYPE = "image/jpeg";

    @BeforeEach
    void setUp() {
        when(mockFile.getOriginalFilename()).thenReturn(PHOTO_NAME);
        when(mockFile.getContentType()).thenReturn(CONTENT_TYPE);
    }

    @Test
    void uploadUserPhoto_WithAutoGeneratedName_ShouldUploadSuccessfully() throws IOException {
        // Arrange
        when(mockFile.getBytes()).thenReturn(PHOTO_DATA);
        when(storageService.uploadPhoto(anyString(), any(byte[].class), eq(CONTENT_TYPE)))
                .thenReturn("users/123/uuid-generated.jpg");

        // Act
        String result = userPhotoService.uploadUserPhoto(USER_ID, mockFile);

        // Assert
        assertNotNull(result);
        assertTrue(result.endsWith(".jpg"));
        verify(storageService).uploadPhoto(
                argThat(path -> path.startsWith("users/123/")),
                eq(PHOTO_DATA),
                eq(CONTENT_TYPE)
        );
    }

    @Test
    void uploadUserPhoto_WithSpecificName_ShouldUploadWithGivenName() throws IOException {
        // Arrange
        when(mockFile.getBytes()).thenReturn(PHOTO_DATA);
        when(storageService.uploadPhoto(anyString(), any(byte[].class), eq(CONTENT_TYPE)))
                .thenReturn("users/123/custom-photo.jpg");

        // Act
        String result = userPhotoService.uploadUserPhoto(USER_ID, "custom-photo.jpg", mockFile);

        // Assert
        assertEquals("custom-photo.jpg", result);
        verify(storageService).uploadPhoto(
                eq("users/123/custom-photo.jpg"),
                eq(PHOTO_DATA),
                eq(CONTENT_TYPE)
        );
    }

    @Test
    void uploadUserAvatar_ShouldUploadWithAvatarName() throws IOException {
        // Arrange
        when(mockFile.getBytes()).thenReturn(PHOTO_DATA);
        when(storageService.uploadPhoto(anyString(), any(byte[].class), eq(CONTENT_TYPE)))
                .thenReturn("users/123/avatar.jpg");

        // Act
        String result = userPhotoService.uploadUserAvatar(USER_ID, mockFile);

        // Assert
        assertEquals("users/123/avatar.jpg", result);
        verify(storageService).uploadPhoto(
                eq("users/123/avatar.jpg"),
                eq(PHOTO_DATA),
                eq(CONTENT_TYPE)
        );
    }

    @Test
    void getUserAvatarUrl_WhenAvatarExists_ShouldReturnUrl() {
        // Arrange
        when(storageService.photoExists("users/123/avatar.jpg")).thenReturn(true);
        when(storageService.getPresignedDownloadUrl("users/123/avatar.jpg", 60))
                .thenReturn("https://storage.example.com/avatar.jpg?token=xyz");

        // Act
        String result = userPhotoService.getUserAvatarUrl(USER_ID, 60);

        // Assert
        assertNotNull(result);
        assertTrue(result.contains("avatar.jpg"));
        verify(storageService).photoExists("users/123/avatar.jpg");
        verify(storageService).getPresignedDownloadUrl("users/123/avatar.jpg", 60);
    }

    @Test
    void getUserAvatarUrl_WhenAvatarDoesNotExist_ShouldReturnNull() {
        // Arrange
        when(storageService.photoExists(anyString())).thenReturn(false);

        // Act
        String result = userPhotoService.getUserAvatarUrl(USER_ID, 60);

        // Assert
        assertNull(result);
        verify(storageService, atLeastOnce()).photoExists(anyString());
        verify(storageService, never()).getPresignedDownloadUrl(anyString(), anyInt());
    }

    @Test
    void listUserPhotos_ShouldReturnPhotoNamesWithoutPrefix() {
        // Arrange
        List<String> fullPaths = Arrays.asList(
                "users/123/photo1.jpg",
                "users/123/photo2.png",
                "users/123/avatar.jpg"
        );
        when(storageService.listPhotos("users/123/")).thenReturn(fullPaths);

        // Act
        List<String> result = userPhotoService.listUserPhotos(USER_ID);

        // Assert
        assertEquals(3, result.size());
        assertTrue(result.contains("photo1.jpg"));
        assertTrue(result.contains("photo2.png"));
        assertTrue(result.contains("avatar.jpg"));
        assertFalse(result.get(0).contains("users/123/"));
    }

    @Test
    void userHasAvatar_WhenAvatarExists_ShouldReturnTrue() {
        // Arrange
        when(storageService.photoExists("users/123/avatar.jpg")).thenReturn(true);

        // Act
        boolean result = userPhotoService.userHasAvatar(USER_ID);

        // Assert
        assertTrue(result);
        verify(storageService).photoExists("users/123/avatar.jpg");
    }

    @Test
    void userHasAvatar_WhenAvatarDoesNotExist_ShouldReturnFalse() {
        // Arrange
        when(storageService.photoExists(anyString())).thenReturn(false);

        // Act
        boolean result = userPhotoService.userHasAvatar(USER_ID);

        // Assert
        assertFalse(result);
    }

    @Test
    void userPhotoExists_WhenPhotoExists_ShouldReturnTrue() {
        // Arrange
        when(storageService.photoExists("users/123/photo.jpg")).thenReturn(true);

        // Act
        boolean result = userPhotoService.userPhotoExists(USER_ID, "photo.jpg");

        // Assert
        assertTrue(result);
        verify(storageService).photoExists("users/123/photo.jpg");
    }

    @Test
    void countUserPhotos_ShouldReturnCorrectCount() {
        // Arrange
        List<String> photos = Arrays.asList(
                "users/123/photo1.jpg",
                "users/123/photo2.jpg",
                "users/123/photo3.jpg"
        );
        when(storageService.listPhotos("users/123/")).thenReturn(photos);

        // Act
        int result = userPhotoService.countUserPhotos(USER_ID);

        // Assert
        assertEquals(3, result);
    }

    @Test
    void getUserPhotoUrl_WhenPhotoExists_ShouldReturnUrl() {
        // Arrange
        when(storageService.photoExists("users/123/photo.jpg")).thenReturn(true);
        when(storageService.getPresignedDownloadUrl("users/123/photo.jpg", 60))
                .thenReturn("https://storage.example.com/photo.jpg?token=xyz");

        // Act
        String result = userPhotoService.getUserPhotoUrl(USER_ID, "photo.jpg", 60);

        // Assert
        assertNotNull(result);
        assertTrue(result.contains("photo.jpg"));
    }

    @Test
    void getUserPhotoUrl_WhenPhotoDoesNotExist_ShouldReturnNull() {
        // Arrange
        when(storageService.photoExists("users/123/photo.jpg")).thenReturn(false);

        // Act
        String result = userPhotoService.getUserPhotoUrl(USER_ID, "photo.jpg", 60);

        // Assert
        assertNull(result);
        verify(storageService, never()).getPresignedDownloadUrl(anyString(), anyInt());
    }

    @Test
    void getAllUserPhotoUrls_ShouldReturnListOfPhotoUrlInfo() {
        // Arrange
        List<String> photos = Arrays.asList(
                "users/123/photo1.jpg",
                "users/123/photo2.jpg"
        );
        when(storageService.listPhotos("users/123/")).thenReturn(photos);
        when(storageService.getPresignedDownloadUrl(anyString(), eq(60)))
                .thenReturn("https://storage.example.com/photo.jpg?token=xyz");

        // Act
        List<UserPhotoService.PhotoUrlInfo> result = userPhotoService.getAllUserPhotoUrls(USER_ID, 60);

        // Assert
        assertEquals(2, result.size());
        assertEquals("photo1.jpg", result.get(0).photoName());
        assertEquals("photo2.jpg", result.get(1).photoName());
        verify(storageService, times(2)).getPresignedDownloadUrl(anyString(), eq(60));
    }
}